### ISSUE TITLE
TileMill stays loading and doesn't open in Yosemite.

### ISSUE THREAD

**Issue by Dapsang** [tilemill-project/tilemill#2497] opened 2015-04-01 08:25 UTC
I've seen this issue elsewhere. The solution was 'check the developer updates and update to that'. That doesn't seem to work for me. I have uninstalled and reinstalled TileMill 6 times now. And keep having the same issue. At the fourth time it managed to load once and I could work that one day. The next day it was the same problem. I have uninstalled TileMill with AppCleaner every time, and on reinstallation I have used previous versions and up to date versions.

Maybe I am missing something? Any suggestions?

**Comment by tmcw** [comment] 2016-11-28 18:43
Duplicate of #2439

**Closed by tmcw** 2016-11-28 18:43 UTC
