### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kocio-pl** [tilemill-project/tilemill#2576] opened 2016-09-29 22:48 UTC
While technically this may be not too important, it would be good for osm-carto [to rely on the released version rather than on master git branch](https://github.com/gravitystorm/openstreetmap-carto/issues/2080#issuecomment-249803296). It would in turn allow dropping MML support in osm-carto and stay with just YAML, which would make the code maintenance easier.

Could you make a new TileMill release or that is not likely to happen for some reasons?

**Comment by tmcw** [comment] 2016-09-29 22:53
Duplicate of #2567

**Closed by tmcw** 2016-09-29 22:53 UTC
