### ISSUE TITLE
Linux installer does not works with Ubuntu 16.x (Xenial Xerus)

### ISSUE THREAD

**Issue by atasc** [tilemill-project/tilemill#2586] opened 2016-11-18 11:31 UTC
Hi,
the Linux installer does not work on Ubuntu 16.x (Xenial Xerus), it generates the following error:

'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''.

**Comment by tmcw** [comment] 2016-11-21 21:41
Duplicate of #2585

**Closed by tmcw** 2016-11-21 21:41 UTC
