### ISSUE TITLE
Not working in Yosemite

### ISSUE THREAD

**Issue by denisedslu** [tilemill-project/tilemill#2498] opened 2015-04-01 21:22 UTC
in app, getting this error: 
[tilemill] Error: listen EADDRINUSE
[tilemill]     at errnoException (net.js:904:11)
[tilemill]     at Server._listen2 (net.js:1042:14)
[tilemill]     at listen (net.js:1064:10)
[tilemill]     at net.js:1146:9
[tilemill]     at dns.js:72:18
[tilemill]     at process._tickDomainCallback (node.js:463:13)
[tilemill]     at Function.Module.runMain (module.js:499:11)
[tilemill]     at startup (node.js:119:16)
[tilemill]     at node.js:906:3

in browser at http://localhost:20009/ getting this error: "Unable to reach the local TileMill Server."

**Comment by tmcw** [comment] 2016-11-28 18:43
Duplicate of #2439

**Closed by tmcw** 2016-11-28 18:43 UTC
